#ifndef __SRC_OBSERVER_INI_SETTING_H__
#define __SRC_OBSERVER_INI_SETTING_H__

//! this document is used for ini setting

#define CLIENT_ADDRESS "CLIENT_ADDRESS"
#define MAX_CONNECTION_NUM "MAX_CONNECTION_NUM"
#define MAX_CONNECTION_NUM_DEFAULT 8192
#define PORT "PORT"
#define PORT_DEFAULT 16880

#define SOCKET_BUFFER_SIZE 8192

#define SESSION_STAGE_NAME "SessionStage"
#endif //__SRC_OBSERVER_INI_SETTING_H__
